export const TelnetOptions = {
  opt2num: {
    IAC: '255',
    DONT: '254',
    DO: '253',
    WONT: '252',
    WILL: '251',
    SB: '250',
    GA: '249',
    EL: '248',
    EC: '247',
    AYT: '246',
    AO: '245',
    IP: '244',
    BREAK: '243',
    DM: '242',
    NOP: '241',
    SE: '240',
    EOR: '239',
    ABORT: '238',
    SUSP: '237',
    SYNCH: '242',
    TELOPT_BINARY: '0',
    TELOPT_ECHO: '1',
    TELOPT_RCP: '2',
    TELOPT_SGA: '3',
    TELOPT_NAMS: '4',
    TELOPT_STATUS: '5',
    TELOPT_TM: '6',
    TELOPT_RCTE: '7',
    TELOPT_NAOL: '8',
    TELOPT_NAOP: '9',
    TELOPT_NAOCRD: '10',
    TELOPT_NAOHTS: '11',
    TELOPT_NAOHTD: '12',
    TELOPT_NAOFFD: '13',
    TELOPT_NAOVTS: '14',
    TELOPT_NAOVTD: '15',
    TELOPT_NAOLFD: '16',
    TELOPT_XASCII: '17',
    TELOPT_LOGOUT: '18',
    TELOPT_BM: '19',
    TELOPT_DET: '20',
    TELOPT_SUPDUP: '21',
    TELOPT_SUPDUPOUTPUT: '22',
    TELOPT_SNDLOC: '23',
    TELOPT_TTYPE: '24',
    TELOPT_EOR: '25',
    TELOPT_TUID: '26',
    TELOPT_OUTMRK: '27',
    TELOPT_TTYLOC: '28',
    TELOPT_NAWS: '31',
    TELOPT_TSPEED: '32',
    TELOPT_LFLOW: '33',
    TELOPT_LINEMODE: '34',
    TELOPT_XDISPLOC: '35',
    TELOPT_ENVIRON: '36',
    TELOPT_AUTHENTICATION: '37',
    TELOPT_ENCRYPT: '38',
    TELOPT_NEWENV: '39',
    TELOPT_CHARSET: '42',
    TELOPT_STARTTLS: '46',
    TELOPT_MSSP: '70',
    TELOPT_COMPRESS: '85',
    TELOPT_MSP: '90',
    TELOPT_MXP: '91',
    TELOPT_ZMP: '93',
    TELOPT_MUSHCLIENT: '102',
    TELOPT_ATCP: '200',
    TELOPT_GMCP: '201',
    TELOPT_EXOPL: '255',
  },
  num2opt: {} as { [key: string]: string },
};

// Initialisieren der num2opt durch Umkehrung von opt2num
for (const key in TelnetOptions.opt2num) {
  TelnetOptions.num2opt[TelnetOptions.opt2num[key]] = key;
}
