export const TelnetCommands = {
  IAC: '/* interpret as command: */',
  DONT: '/* you are not to use option */',
  DO: '/* please, you use option */',
  WONT: '/* I won"t use option */',
  WILL: '/* I will use option */',
  SB: '/* interpret as subnegotiation */',
  GA: '/* you may reverse the line */',
  EL: '/* erase the current line */',
  EC: '/* erase the current character */',
  AYT: '/* are you there */',
  AO: '/* abort output--but let prog finish */',
  IP: '/* interrupt process--permanently */',
  BREAK: '/* break */',
  DM: '/* data mark--for connect. cleaning */',
  NOP: '/* nop */',
  SE: '/* end sub negotiation */',
  EOR: '/* end of record (transparent mode) */',
  ABORT: '/* Abort process */',
  SUSP: '/* Suspend process */',
  SYNCH: '/* for telfunc calls */',
  TELOPT_BINARY: '/* 8-bit data path */',
  TELOPT_ECHO: '/* echo */',
  TELOPT_RCP: '/* prepare to reconnect */',
  TELOPT_SGA: '/* suppress go ahead */',
  TELOPT_NAMS: '/* approximate message size */',
  TELOPT_STATUS: '/* give status */',
  TELOPT_TM: '/* timing mark */',
  TELOPT_RCTE: '/* remote controlled transmission and echo */',
  TELOPT_NAOL: '/* negotiate about output line width */',
  TELOPT_NAOP: '/* negotiate about output page size */',
  TELOPT_NAOCRD: '/* negotiate about CR disposition */',
  TELOPT_NAOHTS: '/* negotiate about horizontal tabstops */',
  TELOPT_NAOHTD: '/* negotiate about horizontal tab disposition */',
  TELOPT_NAOFFD: '/* negotiate about formfeed disposition */',
  TELOPT_NAOVTS: '/* negotiate about vertical tab stops */',
  TELOPT_NAOVTD: '/* negotiate about vertical tab disposition */',
  TELOPT_NAOLFD: '/* negotiate about output LF disposition */',
  TELOPT_XASCII: '/* extended ascic character set */',
  TELOPT_LOGOUT: '/* force logout */',
  TELOPT_BM: '/* byte macro */',
  TELOPT_DET: '/* data entry terminal */',
  TELOPT_SUPDUP: '/* supdup protocol */',
  TELOPT_SUPDUPOUTPUT: '/* supdup output */',
  TELOPT_SNDLOC: '/* send location */',
  TELOPT_TTYPE: '/* terminal type */',
  TELOPT_EOR: '/* end or record */',
  TELOPT_TUID: '/* TACACS user identification */',
  TELOPT_OUTMRK: '/* output marking */',
  TELOPT_TTYLOC: '/* terminal location number */',
  TELOPT_NAWS: '/* window size */',
  TELOPT_TSPEED: '/* terminal speed */',
  TELOPT_LFLOW: '/* remote flow control */',
  TELOPT_LINEMODE: '/* Linemode option */',
  TELOPT_XDISPLOC: '/* X Display Location */',
  TELOPT_ENVIRON: '/* Environment opt for Port ID */',
  TELOPT_AUTHENTICATION: '/* authentication */',
  TELOPT_ENCRYPT: '/* authentication */',
  TELOPT_NEWENV: '/* Environment opt for Port ID */',
  TELOPT_CHARSET: '/* charset */',
  TELOPT_STARTTLS: '/* Transport Layer Security */',
  TELOPT_MSSP: '/* Mud Server Status Protocol */',
  TELOPT_COMPRESS: '/* Mud Compression Protocol, v.1 */',
  TELOPT_MSP: '/* Mud Sound Protocol */',
  TELOPT_MXP: '/* Mud Extension Protocol */',
  TELOPT_ZMP: '/* Zenith Mud Protocol */',
  TELOPT_MUSHCLIENT: '/* Mushclient/Aardwolf Protocol */',
  TELOPT_ATCP: '/* Achaea Telnet Client Protocol */',
  TELOPT_GMCP: '/* Generic MUD Communication Protocol */',
  TELOPT_EXOPL: '/* extended-options-list */',
};
